import{auth,db}from"./firebase.js";
import{signInAnonymously}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import{doc,getDoc,setDoc,updateDoc,deleteDoc,getDocs,query,collection,where,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const FS=window.FS;
const $=id=>document.getElementById(id);
let uid="";
let myCode="";
let selectedFriend="";
const connectionId=(a,b)=>[a,b].sort().join("_");
const makeCode=()=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let code="FS-";for(let i=0;i<6;i++)code+=chars[Math.floor(Math.random()*chars.length)];return code};
const score=(data,targets)=>{data=data||{};targets=targets||{};const calories=Math.min(100,((data.calories||0)/(targets.calories||1))*100);const protein=Math.min(100,((data.protein||0)/(targets.protein||1))*100);const steps=Math.min(100,((data.steps||0)/(targets.steps||1))*100);const exercise=Math.min(100,((data.exercise||0)/30)*100);const sleep=Math.min(100,((data.sleep||0)/(targets.sleep||1))*100);return Math.round((calories+protein+steps+exercise+sleep)/5)};
document.addEventListener("DOMContentLoaded",start);
async function start(){try{FS.nav("friend");const result=await signInAnonymously(auth);uid=result.user.uid;await prepareUser();$("myCodeBox").innerHTML=`<b>${myCode}</b><div class="muted" style="margin-top:5px">Share this code with your friends.</div>`;$("copyCodeBtn").addEventListener("click",copyCode);$("connectBtn").addEventListener("click",sendRequest);await loadFriends();await loadRequests()}catch(error){console.error(error);$("connectMsg").innerHTML=`<div class="notice danger">${error.message}</div>`}}
async function prepareUser(){const data=FS.load();const userRef=doc(db,"users",uid);const userSnap=await getDoc(userRef);if(userSnap.exists()&&userSnap.data().friendCode){myCode=userSnap.data().friendCode}else{while(true){const code=makeCode();const codeSnap=await getDoc(doc(db,"friendCodes",code));if(!codeSnap.exists()){myCode=code;await setDoc(doc(db,"friendCodes",code),{uid:uid});break}}}await setDoc(userRef,{friendCode:myCode,name:data.name||"FitSync User",today:data.today||{},targets:data.targets||{},updatedAt:serverTimestamp()},{merge:true})}
async function copyCode(){try{await navigator.clipboard.writeText(myCode);FS.toast("Friend Code copied")}catch(error){console.error(error);FS.toast("Copy failed")}}
async function sendRequest(){const code=$("friendCode").value.trim().toUpperCase();if(!code){FS.toast("Enter a Friend Code");return}if(code===myCode){FS.toast("You cannot add yourself");return}try{const codeSnap=await getDoc(doc(db,"friendCodes",code));if(!codeSnap.exists()){$("connectMsg").innerHTML='<div class="notice danger">Friend code not found.</div>';return}const friendUid=codeSnap.data().uid;if(friendUid===uid){FS.toast("You cannot add yourself");return}const connectionSnap=await getDoc(doc(db,"connections",connectionId(uid,friendUid)));if(connectionSnap.exists()){$("connectMsg").innerHTML='<div class="notice">This friend is already connected.</div>';return}const requestId=uid+"_"+friendUid;const requestRef=doc(db,"friendRequests",requestId);const oldRequest=await getDoc(requestRef);if(oldRequest.exists()&&oldRequest.data().status==="pending"){$("connectMsg").innerHTML='<div class="notice">Friend request already sent.</div>';return}const data=FS.load();await setDoc(requestRef,{fromUid:uid,toUid:friendUid,fromCode:myCode,fromName:data.name||"FitSync User",status:"pending",createdAt:serverTimestamp()});$("friendCode").value="";$("connectMsg").innerHTML='<div class="notice"><span class="success">Friend request sent.</span></div>';FS.toast("Request sent")}catch(error){console.error(error);$("connectMsg").innerHTML=`<div class="notice danger">${error.message}</div>`}}
async function loadRequests(){const list=$("requestList");try{const requestQuery=query(collection(db,"friendRequests"),where("toUid","==",uid),where("status","==","pending"));const snapshot=await getDocs(requestQuery);if(snapshot.empty){list.innerHTML="No pending friend requests.";return}list.innerHTML="";snapshot.forEach(item=>{const data=item.data();const row=document.createElement("div");row.className="notice";row.style.marginBottom="8px";const name=document.createElement("b");name.textContent=data.fromName||"FitSync User";const code=document.createElement("div");code.className="muted";code.style.marginTop="3px";code.textContent="Code: "+(data.fromCode||"—");const accept=document.createElement("button");accept.className="friend-btn request-action";accept.textContent="Accept";accept.addEventListener("click",()=>acceptRequest(item.id,data.fromUid));row.appendChild(name);row.appendChild(code);row.appendChild(accept);list.appendChild(row)})}catch(error){console.error(error);list.innerHTML=`<div class="notice danger">${error.message}</div>`}}
async function acceptRequest(requestId,friendUid){try{await updateDoc(doc(db,"friendRequests",requestId),{status:"accepted",respondedAt:serverTimestamp()});await setDoc(doc(db,"connections",connectionId(uid,friendUid)),{users:[uid,friendUid],createdAt:serverTimestamp()});FS.toast("Friend connected");await loadRequests();await loadFriends()}catch(error){console.error(error);FS.toast("Could not connect friend")}}
async function loadFriends(){const list=$("friendsList");try{const friendQuery=query(collection(db,"connections"),where("users","array-contains",uid));const snapshot=await getDocs(friendQuery);if(snapshot.empty){list.innerHTML='<tr><td colspan="3" class="muted">No friends connected yet.</td></tr>';clearCompare();return}list.innerHTML="";for(const item of snapshot.docs){const ids=item.data().users||[];const friendUid=ids.find(id=>id!==uid);if(!friendUid)continue;const userSnap=await getDoc(doc(db,"users",friendUid));const data=userSnap.exists()?userSnap.data():{};const row=document.createElement("tr");const nameCell=document.createElement("td");const name=document.createElement("span");name.className="friend-name";name.textContent=data.name||"FitSync Friend";const code=document.createElement("span");code.className="friend-code";code.textContent=data.friendCode||"Friend";nameCell.appendChild(name);nameCell.appendChild(code);const compareCell=document.createElement("td");const compareButton=document.createElement("button");compareButton.className="friend-action";compareButton.textContent="Compare";compareButton.addEventListener("click",()=>selectFriend(friendUid,data.name||"FitSync Friend"));compareCell.appendChild(compareButton);const deleteCell=document.createElement("td");const deleteButton=document.createElement("button");deleteButton.className="friend-action delete-action";deleteButton.textContent="Delete";deleteButton.addEventListener("click",()=>removeFriend(friendUid));deleteCell.appendChild(deleteButton);row.appendChild(nameCell);row.appendChild(compareCell);row.appendChild(deleteCell);list.appendChild(row)}if(!selectedFriend)clearCompare()}catch(error){console.error(error);list.innerHTML=`<tr><td colspan="3"><div class="notice danger">${error.message}</div></td></tr>`}}
async function selectFriend(friendUid,name){selectedFriend=friendUid;await compareFriend(friendUid,name)}
async function compareFriend(friendUid,name){try{const data=FS.load();await setDoc(doc(db,"users",uid),{today:data.today||{},targets:data.targets||{},updatedAt:serverTimestamp()},{merge:true});const friendSnap=await getDoc(doc(db,"users",friendUid));if(!friendSnap.exists()){FS.toast("Friend data unavailable");return}const friend=friendSnap.data();const myPoints=score(data.today,data.targets);const friendPoints=score(friend.today,friend.targets||data.targets);$("myScore").textContent=myPoints;$("friendScore").textContent=friendPoints;$("selectedFriendLabel").textContent=name;$("myScore").style.color=myPoints>friendPoints?"#22d66b":myPoints<friendPoints?"#ff5c5c":"";$("friendScore").style.color=friendPoints>myPoints?"#22d66b":friendPoints<myPoints?"#ff5c5c":"";$("winnerText").className="badge "+(myPoints>friendPoints?"green":myPoints<friendPoints?"red":"gray");$("winnerText").textContent=myPoints>friendPoints?"Your points are higher":myPoints<friendPoints?"Friend's points are higher":"Points are equal";const mine=data.today||{};const theirs=friend.today||{};const rows=[["Health score",myPoints,friendPoints],["Calories",mine.calories||0,theirs.calories||0],["Protein (g)",mine.protein||0,theirs.protein||0],["Fiber (g)",mine.fiber||0,theirs.fiber||0],["Steps",mine.steps||0,theirs.steps||0],["Exercise (min)",mine.exercise||0,theirs.exercise||0],["Sleep (h)",mine.sleep||0,theirs.sleep||0]];$("compareTable").innerHTML=rows.map(row=>{const difference=Math.round((row[1]-row[2])*10)/10;const className=difference>0?"success":difference<0?"danger":"muted";return`<tr><td>${row[0]}</td><td>${row[1]}</td><td>${row[2]}</td><td class="${className}">${difference>0?"+":""}${difference}</td></tr>`}).join("")}catch(error){console.error(error);FS.toast("Comparison failed")}}
function clearCompare(){const data=FS.load();$("myScore").textContent=score(data.today,data.targets);$("friendScore").textContent=0;$("selectedFriendLabel").textContent="Select a friend";$("winnerText").className="badge gray";$("winnerText").textContent="Select a friend to compare";$("compareTable").innerHTML='<tr><td colspan="4" class="muted">Select a friend to compare.</td></tr>'}
async function removeFriend(friendUid){if(!confirm("Delete this friend connection?"))return;try{await deleteDoc(doc(db,"connections",connectionId(uid,friendUid)));if(selectedFriend===friendUid)selectedFriend="";FS.toast("Friend removed");await loadFriends()}catch(error){console.error(error);FS.toast("Could not remove friend")}}