import{auth,db}from"./firebase.js";import{signInAnonymously}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";import{doc,getDoc,setDoc,updateDoc,deleteDoc,getDocs,query,collection,where,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";
const FS=window.FS,$=id=>document.getElementById(id);let uid="",myCode="",selectedFriend="";
const connectionId=(a,b)=>[a,b].sort().join("_");
const makeCode=()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let x="FS-";for(let i=0;i<6;i++)x+=c[Math.floor(Math.random()*c.length)];return x};
const score=(n,t)=>{n=n||{};t=t||{};const a=Math.min(100,((n.calories||0)/(t.calories||1))*100),b=Math.min(100,((n.protein||0)/(t.protein||1))*100),c=Math.min(100,((n.steps||0)/(t.steps||1))*100),d=Math.min(100,((n.exercise||0)/30)*100),e=Math.min(100,((n.sleep||0)/(t.sleep||1))*100);return Math.round((a+b+c+d+e)/5)};
document.addEventListener("DOMContentLoaded",start);
async function start(){try{FS.nav("friend");const r=await signInAnonymously(auth);uid=r.user.uid;await prepareUser();$("myCodeBox").innerHTML=`<b>${myCode}</b><div class="muted" style="margin-top:5px">Share this code with your friends.</div>`;$("copyCodeBtn").onclick=copyCode;$("connectBtn").onclick=sendRequest;await loadFriends();await loadRequests()}catch(e){console.error(e);$("connectMsg").innerHTML=`<div class="notice danger">${e.message}</div>`}}
async function prepareUser(){const d=FS.load(),ref=doc(db,"users",uid),s=await getDoc(ref);if(s.exists()&&s.data().friendCode)myCode=s.data().friendCode;else{while(true){const c=makeCode(),x=await getDoc(doc(db,"friendCodes",c));if(!x.exists()){myCode=c;await setDoc(doc(db,"friendCodes",c),{uid});break}}}await setDoc(ref,{friendCode:myCode,name:d.name||"FitSync User",today:d.today||{},targets:d.targets||{},updatedAt:serverTimestamp()},{merge:true})}
async function copyCode(){try{await navigator.clipboard.writeText(myCode);FS.toast("Friend Code copied")}catch(e){FS.toast("Copy failed")}}
async function sendRequest(){const code=$("friendCode").value.trim().toUpperCase();if(!code){FS.toast("Enter a Friend Code");return}if(code===myCode){FS.toast("You cannot add yourself");return}try{const s=await getDoc(doc(db,"friendCodes",code));if(!s.exists()){$("connectMsg").innerHTML='<div class="notice danger">Friend code not found.</div>';return}const fid=s.data().uid;if(fid===uid){FS.toast("You cannot add yourself");return}const con=await getDoc(doc(db,"connections",connectionId(uid,fid)));if(con.exists()){$("connectMsg").innerHTML='<div class="notice">This friend is already connected.</div>';return}const ref=doc(db,"friendRequests",uid+"_"+fid),old=await getDoc(ref);if(old.exists()&&old.data().status==="pending"){$("connectMsg").innerHTML='<div class="notice">Friend request already sent.</div>';return}const d=FS.load();await setDoc(ref,{fromUid:uid,toUid:fid,fromCode:myCode,fromName:d.name||"FitSync User",status:"pending",createdAt:serverTimestamp()});$("friendCode").value="";$("connectMsg").innerHTML='<div class="notice"><span class="success">Friend request sent.</span></div>';FS.toast("Request sent")}catch(e){console.error(e);$("connectMsg").innerHTML=`<div class="notice danger">${e.message}</div>`}}
async function loadRequests(){const list=$("requestList");try{const q=query(collection(db,"friendRequests"),where("toUid","==",uid),where("status","==","pending")),s=await getDocs(q);if(s.empty){list.innerHTML="No pending friend requests.";return}list.innerHTML="";s.forEach(x=>{const d=x.data(),row=document.createElement("div");row.className="notice";row.style.marginBottom="8px";row.innerHTML=`<b>${d.fromName||"FitSync User"}</b><div class="muted">Code: ${d.fromCode||"—"}</div>`;const a=document.createElement("button");a.className="friend-small-btn request-action";a.textContent="Accept";a.onclick=()=>acceptRequest(x.id,d.fromUid);row.appendChild(a);list.appendChild(row)})}catch(e){console.error(e);list.innerHTML=`<div class="notice danger">${e.message}</div>`}}
async function acceptRequest(id,fid){try{await updateDoc(doc(db,"friendRequests",id),{status:"accepted",respondedAt:serverTimestamp()});await setDoc(doc(db,"connections",connectionId(uid,fid)),{users:[uid,fid],createdAt:serverTimestamp()});FS.toast("Friend connected");await loadRequests();await loadFriends()}catch(e){console.error(e);FS.toast("Could not connect friend")}}
async function loadFriends(){const list=$("friendsList");try{const q=query(collection(db,"connections"),where("users","array-contains",uid)),s=await getDocs(q);if(s.empty){list.innerHTML='<tr><td colspan="3" class="muted">No friends connected yet.</td></tr>';clearCompare();return}list.innerHTML="";for(const x of s.docs){const ids=x.data().users,fid=ids.find(v=>v!==uid);if(!fid)continue;const us=await getDoc(doc(db,"users",fid)),d=us.exists()?us.data():{};const row=document.createElement("tr");const name=document.createElement("td");name.innerHTML=`<b>${d.name||"FitSync Friend"}</b>`;const compareCell=document.createElement("td");const compare=document.createElement("button");compare.className="friend-action";compare.textContent="Compare";compare.onclick=()=>selectFriend(fid,d.name||"FitSync Friend");compareCell.appendChild(compare);const deleteCell=document.createElement("td");const remove=document.createElement("button");remove.className="friend-action delete-action";remove.textContent="Delete";remove.onclick=()=>removeFriend(fid);deleteCell.appendChild(remove);row.appendChild(name);row.appendChild(compareCell);row.appendChild(deleteCell);list.appendChild(row)}if(!selectedFriend)clearCompare()}catch(e){console.error(e);list.innerHTML=`<tr><td colspan="3"><div class="notice danger">${e.message}</div></td></tr>`}}
async function selectFriend(fid,name){selectedFriend=fid;await compareFriend(fid,name)}
async function compareFriend(fid,name){try{const d=FS.load();await setDoc(doc(db,"users",uid),{today:d.today||{},targets:d.targets||{},updatedAt:serverTimestamp()},{merge:true});const s=await getDoc(doc(db,"users",fid));if(!s.exists())return;const f=s.data(),my=score(d.today,d.targets),fs=score(f.today,f.targets||d.targets);$("myScore").textContent=my;$("friendScore").textContent=fs;$("selectedFriendLabel").textContent=name;$("myScore").style.color=my>fs?"#22d66b":my<fs?"#ff5c5c":"";$("friendScore").style.color=fs>my?"#22d66b":fs<my?"#ff5c5c":"";$("winnerText").className="badge "+(my>fs?"green":my<fs?"red":"gray");$("winnerText").textContent=my>fs?"Your points are higher":my<fs?"Friend's points are higher":"Points are equal";const n=d.today||{},z=f.today||{},rows=[["Health score",my,fs],["Calories",n.calories||0,z.calories||0],["Protein (g)",n.protein||0,z.protein||0],["Fiber (g)",n.fiber||0,z.fiber||0],["Steps",n.steps||0,z.steps||0],["Exercise (min)",n.exercise||0,z.exercise||0],["Sleep (h)",n.sleep||0,z.sleep||0]];$("compareTable").innerHTML=rows.map(r=>{const dif=Math.round((r[1]-r[2])*10)/10;return`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td class="${dif>0?"success":dif<0?"danger":"muted"}">${dif>0?"+":""}${dif}</td></tr>`}).join("")}catch(e){console.error(e)}}
function clearCompare(){const d=FS.load();$("myScore").textContent=score(d.today,d.targets);$("friendScore").textContent=0;$("selectedFriendLabel").textContent="Select a friend";$("winnerText").className="badge gray";$("winnerText").textContent="Select a friend to compare";$("compareTable").innerHTML='<tr><td colspan="4" class="muted">Select a friend to compare.</td></tr>'}
async function removeFriend(fid){if(!confirm("Delete this friend connection?"))return;try{await deleteDoc(doc(db,"connections",connectionId(uid,fid)));if(selectedFriend===fid)selectedFriend="";FS.toast("Friend removed");await loadFriends()}catch(e){console.error(e);FS.toast("Could not remove friend")}}